import { PhotoItem, Collection } from '../types';

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: 'col-analog-street',
    name: 'Analog Street & Shadows',
    description: 'Documentary studies in urban geometry, high contrast light, and quiet human moments.',
    createdAt: Date.now() - 86400000 * 45,
    curatorNote: 'Captured predominantly on 35mm Tri-X 400 and Portra 160 across temperate European arcades.',
  },
  {
    id: 'col-botanical-forms',
    name: 'Botanical & Mineral Studies',
    description: 'Minimalist macro captures of organic flora, mineral veins, and earth textures.',
    createdAt: Date.now() - 86400000 * 30,
    curatorNote: 'Focus on natural pigments and tactile surface rhythms under diffused northern skylight.',
  },
  {
    id: 'col-coastal-solitude',
    name: 'Coastal Solitude',
    description: 'Atmospheric seascapes, dunes, and twilight horizons exploring quiet expanse.',
    createdAt: Date.now() - 86400000 * 15,
    curatorNote: 'Emphasizing the blue hour spectrum and slow shutter ocean textures.',
  },
];

export const INITIAL_PHOTOS: PhotoItem[] = [
  {
    id: 'photo-1',
    title: 'Arcade at Noon Light',
    src: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1400&q=85',
    aspectRatio: 1.5,
    dateAdded: Date.now() - 86400000 * 10,
    dateTaken: '2024-05-18',
    collectionId: 'col-analog-street',
    tags: ['Architecture', 'Monochrome', 'Shadows', 'Minimal'],
    notes: 'Raking noon sunlight cutting through concrete columns. Clean chiaroscuro balance.',
    dominantFamily: 'monochrome',
    palette: [
      { hex: '#1C1B1A', rgb: [28, 27, 26], name: 'Charcoal Noir', family: 'monochrome' },
      { hex: '#8F8982', rgb: [143, 137, 130], name: 'Titanium Slate', family: 'monochrome' },
      { hex: '#DED8CE', rgb: [222, 216, 206], name: 'Parchment Glow', family: 'warm' },
      { hex: '#5E5851', rgb: [94, 88, 81], name: 'Silver Grain', family: 'monochrome' },
    ],
    exif: {
      camera: 'Leica M6',
      lens: 'Summicron 35mm f/2',
      focalLength: '35mm',
      aperture: 'f/5.6',
      shutterSpeed: '1/500s',
      iso: '400',
      filmStock: 'Kodak Tri-X 400',
      location: 'Milan, Italy',
      year: '2024',
    },
    adjustments: { brightness: 0, contrast: 10, saturation: -100, warmth: 0, sepia: 0, grain: 25, vignette: 10 },
    rating: 5,
    isFavorite: true,
    frameStyle: 'museum-mat',
    fileSize: 420000,
  },
  {
    id: 'photo-2',
    title: 'Eucalyptus in Morning Mist',
    src: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1400&q=85',
    aspectRatio: 1.5,
    dateAdded: Date.now() - 86400000 * 8,
    dateTaken: '2024-06-02',
    collectionId: 'col-botanical-forms',
    tags: ['Botanical', 'Forest', 'Fog', 'Muted'],
    notes: 'Early mist rising between damp silver trunks. Rich evergreen silence.',
    dominantFamily: 'sage',
    palette: [
      { hex: '#3B4D3C', rgb: [59, 77, 60], name: 'Olive Sage', family: 'sage' },
      { hex: '#8B9A84', rgb: [139, 154, 132], name: 'Muted Moss', family: 'sage' },
      { hex: '#D4DDD1', rgb: [212, 221, 209], name: 'Verdant Mint', family: 'sage' },
      { hex: '#212A22', rgb: [33, 42, 34], name: 'Forest Slate', family: 'sage' },
    ],
    exif: {
      camera: 'Hasselblad 500C/M',
      lens: 'Zeiss Planar 80mm f/2.8',
      focalLength: '80mm',
      aperture: 'f/4',
      shutterSpeed: '1/60s',
      iso: '160',
      filmStock: 'Fujifilm Pro 400H',
      location: 'Black Forest, Germany',
      year: '2024',
    },
    adjustments: { brightness: 5, contrast: -5, saturation: 5, warmth: -10, sepia: 0, grain: 15, vignette: 5 },
    rating: 5,
    isFavorite: true,
    frameStyle: 'walnut-frame',
    fileSize: 580000,
  },
  {
    id: 'photo-3',
    title: 'Aegean Dusk & Sea Foam',
    src: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=85',
    aspectRatio: 1.5,
    dateAdded: Date.now() - 86400000 * 6,
    dateTaken: '2024-07-14',
    collectionId: 'col-coastal-solitude',
    tags: ['Coast', 'Azure', 'Horizon', 'Atmospheric'],
    notes: 'Tide receding across wet sandstone at dusk. Deep cobalt gradient meeting violet reflections.',
    dominantFamily: 'azure',
    palette: [
      { hex: '#1E3A5F', rgb: [30, 58, 95], name: 'Deep Indigo', family: 'azure' },
      { hex: '#527B9B', rgb: [82, 123, 155], name: 'Cobalt Cyan', family: 'azure' },
      { hex: '#C2D7E5', rgb: [194, 215, 229], name: 'Aegean Mist', family: 'azure' },
      { hex: '#D99B6A', rgb: [217, 155, 106], name: 'Terracotta', family: 'amber' },
    ],
    exif: {
      camera: 'Sony A7IV',
      lens: 'FE 24-70mm f/2.8 GM II',
      focalLength: '45mm',
      aperture: 'f/8',
      shutterSpeed: '1/15s',
      iso: '100',
      location: 'Crete, Greece',
      year: '2024',
    },
    adjustments: { brightness: 0, contrast: 15, saturation: 10, warmth: 0, sepia: 0, grain: 5, vignette: 15 },
    rating: 4,
    isFavorite: false,
    frameStyle: 'slide-mount',
    fileSize: 490000,
  },
  {
    id: 'photo-4',
    title: 'Dune Crest in Amber Saffron',
    src: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1400&q=85',
    aspectRatio: 1.5,
    dateAdded: Date.now() - 86400000 * 5,
    dateTaken: '2024-04-09',
    collectionId: 'col-coastal-solitude',
    tags: ['Desert', 'Amber', 'Earth', 'Minimalist'],
    notes: 'Wind-carved ridges in evening warmth. Knife-edge ridge separating shadow and gold.',
    dominantFamily: 'amber',
    palette: [
      { hex: '#C87D38', rgb: [200, 125, 56], name: 'Warm Amber', family: 'amber' },
      { hex: '#E7B576', rgb: [231, 181, 118], name: 'Honey Ochre', family: 'amber' },
      { hex: '#7A431D', rgb: [122, 67, 29], name: 'Terracotta', family: 'earth' },
      { hex: '#F6E4CA', rgb: [246, 228, 202], name: 'Parchment Glow', family: 'warm' },
    ],
    exif: {
      camera: 'Fujifilm GFX 100S',
      lens: 'GF 110mm f/2',
      focalLength: '110mm',
      aperture: 'f/5.6',
      shutterSpeed: '1/320s',
      iso: '200',
      location: 'Namib Desert',
      year: '2024',
    },
    adjustments: { brightness: 0, contrast: 5, saturation: 8, warmth: 15, sepia: 0, grain: 10, vignette: 5 },
    rating: 5,
    isFavorite: true,
    frameStyle: 'museum-mat',
    fileSize: 620000,
  },
  {
    id: 'photo-5',
    title: 'Red Neon & Kyoto Rain',
    src: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1400&q=85',
    aspectRatio: 1.5,
    dateAdded: Date.now() - 86400000 * 4,
    dateTaken: '2024-03-22',
    collectionId: 'col-analog-street',
    tags: ['Street', 'Crimson', 'Night', 'Rain'],
    notes: 'Reflected car lights pooling on wet asphalt. Crimson lanterns through umbrella ribs.',
    dominantFamily: 'crimson',
    palette: [
      { hex: '#A8242A', rgb: [168, 36, 42], name: 'Crimson Flame', family: 'crimson' },
      { hex: '#4A1217', rgb: [74, 18, 23], name: 'Burgundy Velvet', family: 'crimson' },
      { hex: '#161314', rgb: [22, 19, 20], name: 'Pure Obsidian', family: 'monochrome' },
      { hex: '#E57D84', rgb: [229, 125, 132], name: 'Rose Oxide', family: 'crimson' },
    ],
    exif: {
      camera: 'Contax T2',
      lens: 'Carl Zeiss Sonnar 38mm f/2.8',
      focalLength: '38mm',
      aperture: 'f/2.8',
      shutterSpeed: '1/60s',
      iso: '800',
      filmStock: 'Cinestill 800T',
      location: 'Gion, Kyoto, Japan',
      year: '2024',
    },
    adjustments: { brightness: -5, contrast: 15, saturation: 15, warmth: 10, sepia: 0, grain: 30, vignette: 20 },
    rating: 5,
    isFavorite: true,
    frameStyle: 'polaroid',
    fileSize: 510000,
  },
  {
    id: 'photo-6',
    title: 'Terracotta Urn & Dried Seedheads',
    src: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1400&q=85',
    aspectRatio: 1.5,
    dateAdded: Date.now() - 86400000 * 3,
    dateTaken: '2024-08-11',
    collectionId: 'col-botanical-forms',
    tags: ['Earth', 'Still Life', 'Warm', 'Texture'],
    notes: 'Delicate dried lunaria seedpods resting alongside unglazed earthen clay vessel.',
    dominantFamily: 'earth',
    palette: [
      { hex: '#633B26', rgb: [99, 59, 38], name: 'Raw Umber', family: 'earth' },
      { hex: '#A86C45', rgb: [168, 108, 69], name: 'Burnt Clay', family: 'earth' },
      { hex: '#D2B395', rgb: [210, 179, 149], name: 'Sepia Dune', family: 'earth' },
      { hex: '#261912', rgb: [38, 25, 18], name: 'Espresso Soil', family: 'earth' },
    ],
    exif: {
      camera: 'Canon EOS R5',
      lens: 'RF 85mm f/1.2L USM',
      focalLength: '85mm',
      aperture: 'f/2',
      shutterSpeed: '1/200s',
      iso: '100',
      location: 'Provence, France',
      year: '2024',
    },
    adjustments: { brightness: 0, contrast: 0, saturation: -5, warmth: 20, sepia: 15, grain: 15, vignette: 10 },
    rating: 4,
    isFavorite: false,
    frameStyle: 'museum-mat',
    fileSize: 460000,
  },
  {
    id: 'photo-7',
    title: 'Passage in Old Lisbon',
    src: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=1400&q=85',
    aspectRatio: 1.5,
    dateAdded: Date.now() - 86400000 * 2,
    dateTaken: '2024-05-30',
    collectionId: 'col-analog-street',
    tags: ['Street', 'Warm', 'Shadows', 'Sunlight'],
    notes: 'Sunbeams hitting faded yellow lime-washed facade and cast-iron balcony shadow.',
    dominantFamily: 'warm',
    palette: [
      { hex: '#D99F48', rgb: [217, 159, 72], name: 'Warm Ochre', family: 'warm' },
      { hex: '#F0D597', rgb: [240, 213, 151], name: 'Parchment Glow', family: 'warm' },
      { hex: '#453523', rgb: [69, 53, 35], name: 'Raw Umber', family: 'earth' },
      { hex: '#7D6442', rgb: [125, 100, 66], name: 'Weathered Cedar', family: 'earth' },
    ],
    exif: {
      camera: 'Fujifilm X100V',
      lens: 'Fujinon 23mm f/2',
      focalLength: '23mm',
      aperture: 'f/4',
      shutterSpeed: '1/1000s',
      iso: '320',
      filmStock: 'Kodak Portra 400',
      location: 'Alfama, Lisbon',
      year: '2024',
    },
    adjustments: { brightness: 5, contrast: 10, saturation: 5, warmth: 25, sepia: 5, grain: 20, vignette: 5 },
    rating: 4,
    isFavorite: false,
    frameStyle: 'minimal',
    fileSize: 530000,
  },
  {
    id: 'photo-8',
    title: 'Icelandic Black Sand & Ice Fragment',
    src: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1400&q=85',
    aspectRatio: 1.5,
    dateAdded: Date.now() - 86400000 * 1,
    dateTaken: '2024-09-03',
    collectionId: 'col-coastal-solitude',
    tags: ['Monochrome', 'Ice', 'Basalt', 'Fine Art'],
    notes: 'Translucent glacial crystal resting on volcanic black basalt sand. Diamond light prism.',
    dominantFamily: 'monochrome',
    palette: [
      { hex: '#0F0E0E', rgb: [15, 14, 14], name: 'Pure Obsidian', family: 'monochrome' },
      { hex: '#403D3B', rgb: [64, 61, 59], name: 'Charcoal Noir', family: 'monochrome' },
      { hex: '#9E9995', rgb: [158, 153, 149], name: 'Silver Grain', family: 'monochrome' },
      { hex: '#EBE7E2', rgb: [235, 231, 226], name: 'Alabaster', family: 'monochrome' },
    ],
    exif: {
      camera: 'Leica SL2',
      lens: 'Apo-Summicron-SL 50mm f/2 ASPH',
      focalLength: '50mm',
      aperture: 'f/8',
      shutterSpeed: '1/250s',
      iso: '50',
      location: 'Diamond Beach, Iceland',
      year: '2024',
    },
    adjustments: { brightness: 0, contrast: 20, saturation: -100, warmth: 0, sepia: 0, grain: 10, vignette: 10 },
    rating: 5,
    isFavorite: true,
    frameStyle: 'museum-mat',
    fileSize: 670000,
  },
];
